$(function () {
		$('#loio4034a659577d4d5fa725af4c3525eb2d____im_imagemap1').wrapAll("<div class='autogenerated sectiondiv main' id='loio4034a659577d4d5fa725af4c3525eb2d__im_imagewrapper1'></div>");
	
		$('#loio4034a659577d4d5fa725af4c3525eb2d__main').mapster( 
		
		
		
    {
      "singleSelect": true,
      "clickNavigate": false,
      "showToolTip": true,
      "mapKey": "id",
      "toolTipContainer": "<div class='colorful_toolip' style='max-width:15em; background: #FFFFFF; font:1.2em Arial, sans-serif; padding:0.8em; margin:0.5em; border:0.5em; border: 2px solid #87afb2'></div>",
      "toolTipClose": ["area-click","area-mouseout"],
      "fillOpacity": 0.15,
      "render_highlight": 
    {
      "fillColor": "000000",
      "stroke": false},
      "render_select": 
    {
      "fillColor": "000000",
      "stroke": false},
      "onClick": function(e) { show_divs1(e.key) },
      "areas": [
    {
      "key": "im1",
      "toolTip": $("#im1").attr("title")},
    {
      "key": "im2",
      "toolTip": $("#im2").attr("title")},
    {
      "key": "im3",
      "toolTip": $("#im3").attr("title")},
    {
      "key": "im4",
      "toolTip": $("#im4").attr("title")},
    {
      "key": "im5",
      "toolTip": $("#im5").attr("title")},
    {
      "key": "im6",
      "toolTip": $("#im6").attr("title")},
    {
      "key": "im7",
      "toolTip": $("#im7").attr("title")},
    {
      "key": "im8",
      "toolTip": $("#im8").attr("title")}]}
		);
		
		$('div[id="loio4034a659577d4d5fa725af4c3525eb2d____im_imagemap1"] area').each(function() {
		var $elem = $(this);
		var savealt = $elem.attr('alt');
		var savetitle = $elem.attr('title');
		$elem.hover(function(){
		$elem.removeAttr('title').removeAttr('alt')
		},function(){
		$elem.attr({title:savetitle,alt:savealt});
		});
		})
	
		$('#loio4034a659577d4d5fa725af4c3525eb2d__im_imagewrapper1 ~ .visibility-trigger').hide();
		$('div[id$="subsection-im0"]').show();
	
		$( "#loio4034a659577d4d5fa725af4c3525eb2d__im_imagewrapper1" ).mouseenter(function() {  
		if ($('#loio4034a659577d4d5fa725af4c3525eb2d__main').width() < 574){	
		$('#loio4034a659577d4d5fa725af4c3525eb2d__main').mapster('resize',574,0,200);  
			}
			});
			
		function show_divs1(divID){
		$('#loio4034a659577d4d5fa725af4c3525eb2d__main').mapster('resize',200,0,200); 
			$('#loio4034a659577d4d5fa725af4c3525eb2d__im_imagewrapper1 ~ .visibility-trigger').hide();
			$('div[id$="'+divID+'"]').show();
		}
	
		$( "#loio4034a659577d4d5fa725af4c3525eb2d__im_imagewrapper1 ~ .visibility-trigger > p.subsection_title" ).css("color", "#87afb2" );
	});